-- Retrieve all data from all tables
SELECT * FROM TRIP;
SELECT * FROM PASSENGER;
SELECT * FROM DRIVER;
SELECT * FROM VEHICLE;
SELECT * FROM ROUTE;
SELECT * FROM STOP;
SELECT * FROM REGISTRATION;
SELECT * FROM INCLUDES;

-- Count number of rows in each table
SELECT 'TRIP' AS table_name, COUNT(*) FROM TRIP;
SELECT 'PASSENGER' AS table_name, COUNT(*) FROM PASSENGER;
SELECT 'DRIVER' AS table_name, COUNT(*) FROM DRIVER;
SELECT 'VEHICLE' AS table_name, COUNT(*) FROM VEHICLE;
SELECT 'ROUTE' AS table_name, COUNT(*) FROM ROUTE;
SELECT 'STOP' AS table_name, COUNT(*) FROM STOP;
SELECT 'REGISTRATION' AS table_name, COUNT(*) FROM REGISTRATION;
SELECT 'INCLUDES' AS table_name, COUNT(*) FROM INCLUDES;