-- Drop tables with foreign keys first
DROP TABLE IF EXISTS REGISTRATION;
DROP TABLE IF EXISTS INCLUDES;

-- Drop dependent tables
DROP TABLE IF EXISTS TRIP;

-- Drop base tables
DROP TABLE IF EXISTS PASSENGER;
DROP TABLE IF EXISTS DRIVER;
DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS ROUTE;
DROP TABLE IF EXISTS STOP;